In [11]:
import numpy as np
import requests


# Get Input

In [12]:
puzzle_input = 6042

# Part 1

In [123]:
grid_x, grid_y = 300, 300
power_grid = np.zeros((grid_x,grid_y))
serial_number = 18 #puzzle_input 

In [124]:
for i in range(grid_y):
    for j in range(grid_x):
        rack_id = j + 1 + 10
        power_level = rack_id * (i+1)
        power_level += serial_number
        power_level *= rack_id
        hundreds_digit = int(str(power_level)[-3]) if len(str(power_level))>=3 else 0
        power_grid[i][j] = hundreds_digit - 5
        
    
    

In [125]:
power_grid_3x3 = np.zeros((grid_x, grid_y))
power_grid_3x3[:-1,:-1] += power_grid[1:,1:]
power_grid_3x3[:-1,:] += power_grid[1:,:]
power_grid_3x3[:-1,1:] += power_grid[1:,:-1]
power_grid_3x3[:,:-1] += power_grid[:,1:]
power_grid_3x3[:,:] += power_grid[:,:]
power_grid_3x3[:,1:] += power_grid[:,:-1]
power_grid_3x3[1:,:-1] += power_grid[:-1,1:]
power_grid_3x3[1:,:] += power_grid[:-1,:]
power_grid_3x3[1:,1:] += power_grid[:-1,:-1]

In [126]:
power_grid[:-1,:-1]

array([[-2., -2., -1., ...,  2., -1., -5.],
       [-1.,  0.,  0., ..., -5., -3.,  0.],
       [ 0.,  1.,  2., ..., -3., -4., -5.],
       ...,
       [-4.,  4., -1., ..., -1., -4., -1.],
       [-3., -4.,  0., ...,  2., -5.,  4.],
       [-2., -3.,  2., ...,  4.,  3., -2.]])

In [127]:
power_grid_3x3

array([[ -5.,  -6.,  -3., ..., -12.,  -6.,  -2.],
       [ -4.,  -3.,   3., ..., -24., -12.,  -4.],
       [  3.,   9.,   8., ..., -26.,  -9.,   3.],
       ...,
       [-12., -11.,   1., ...,   0., -11.,  -5.],
       [-14.,  -8.,  -3., ...,   8.,   2.,   2.],
       [ -7.,  -1.,   0., ...,   7.,   5.,   0.]])

In [128]:
(y,x) = np.unravel_index(np.argmax(power_grid_3x3, axis=None), power_grid_3x3.shape)
x,y

(33, 45)

# Part 2

In [173]:
grid_x, grid_y = 300, 300
power_grid = np.zeros((grid_x,grid_y))
serial_number = puzzle_input 

In [174]:
for i in range(grid_y):
    for j in range(grid_x):
        rack_id = j + 1 + 10
        power_level = rack_id * (i+1)
        power_level += serial_number
        power_level *= rack_id
        hundreds_digit = int(str(power_level)[-3]) if len(str(power_level))>=3 else 0
        power_grid[i][j] = hundreds_digit - 5
           

In [175]:
max_id = None
max_value = np.NINF

for j in range(grid_x):
    for i in range(grid_y):
        max_k = min(grid_y-i, grid_x-j)
        power = 0  #power_grid[i,j]
        for k in range(max_k):
            power+=sum(power_grid[i:(i+k+1),j+k])
            power+=sum(power_grid[i+k,j:(j+k+1)])
            power-= power_grid[i+k,j+k]
            if power > max_value:
                max_id = (j+1,i+1,k+1)
                max_value = power
                print("new max: {} at {}".format(max_value, max_id))

new max: 0.0 at (1, 1, 1)
new max: 5.0 at (1, 1, 2)
new max: 12.0 at (1, 1, 3)
new max: 14.0 at (1, 35, 3)
new max: 15.0 at (1, 35, 4)
new max: 17.0 at (1, 36, 3)
new max: 18.0 at (1, 43, 3)
new max: 21.0 at (11, 57, 12)
new max: 35.0 at (11, 265, 12)
new max: 40.0 at (12, 265, 12)
new max: 45.0 at (12, 266, 11)
new max: 50.0 at (13, 265, 11)
new max: 53.0 at (13, 265, 12)
new max: 55.0 at (13, 266, 10)
new max: 60.0 at (13, 266, 11)
new max: 64.0 at (95, 212, 11)
new max: 65.0 at (165, 25, 11)
new max: 69.0 at (165, 25, 13)
new max: 70.0 at (228, 249, 16)
new max: 78.0 at (229, 249, 15)
new max: 80.0 at (229, 250, 15)
new max: 92.0 at (230, 249, 14)
new max: 93.0 at (230, 251, 14)
new max: 98.0 at (231, 249, 13)
new max: 104.0 at (231, 249, 14)
new max: 106.0 at (231, 250, 13)
new max: 107.0 at (232, 249, 12)
new max: 114.0 at (232, 250, 13)
new max: 119.0 at (232, 251, 12)


In [176]:
# Binary 2d Sum
# compute sum of squares of size (1,2,4,8,16, etc. starting i,j for each i,j)
# then can compute a sum 

In [178]:
power_grid[10:20:5,1:2]

array([[-5.],
       [ 3.]])

In [230]:
binary_sums = {}
binary_sums[1] = power_grid
prev_binary_sum = power_grid
for i in range(0,8):
    k = 2**i
    curr_binary_sum = np.zeros((grid_y, grid_x))
    
    for i in range(grid_y-2*k):
        for j in range(grid_x-2*k):
            curr_binary_sum[i,j] = prev_binary_sum[i,j]
            
            curr_binary_sum[i,j] += sum(prev_binary_sum[i:(i+k+1):k, j+k])
            curr_binary_sum[i,j] += sum(prev_binary_sum[i+k, j:(j+k+1):k])
            curr_binary_sum[i,j] -= prev_binary_sum[i+k,j+k]
    
    binary_sums[2*k] = copy.copy(curr_binary_sum)
    prev_binary_sum = curr_binary_sum
    

    
    




In [231]:
power_grid[0:5,0:5]

array([[ 0.,  1.,  2.,  2.,  3.],
       [ 2.,  2.,  3.,  4., -5.],
       [ 3.,  4., -5., -4., -2.],
       [ 4., -5., -3., -2.,  0.],
       [-5., -3., -2.,  0.,  2.]])

In [234]:
binary_sums[128][25:32,25:32]

array([[-8887., -8892., -8889., -8897., -8948., -8890., -8897.],
       [-8964., -8960., -8961., -8976., -9026., -8969., -8979.],
       [-8997., -8984., -8979., -9001., -9039., -8974., -8987.],
       [-9033., -9021., -9011., -9039., -9087., -9023., -9040.],
       [-8946., -8946., -8940., -8965., -9012., -8959., -8980.],
       [-8947., -8949., -8947., -8968., -9024., -8972., -8997.],
       [-8979., -8983., -8976., -8994., -9049., -8989., -9008.]])

In [241]:
s = 128
i,j= 25,31
np.sum(power_grid[i:(i+s),j:(j+s)])

-8897.0

In [225]:
def sum_square(grid, i,j,k):
    bk = int(np.log2(k))
    rem = 
    
    

-7.0

In [243]:
int(np.log2(54))

5